// scripts/update-aliases.py가 만든 파일이다. 손으로 고치지 말고 스크립트를 다시 돌린다.
// 출처: Wikidata (CC0) 가상의 인물 항목의 한국어 이름

extension KoreanAliases {
    static let generated: [String: [String]] = [
        "「시드」": ["seed"],
        "가디언": ["guardian"],
        "각청": ["keqing"],
        "간달프": ["gandalf"],
        "거츠": ["guts"],
        "경류": ["jingliu"],
        "경찰관": ["copper"],
        "경찰관A": ["copper"],
        "계왕": ["kai"],
        "고스트": ["ghost"],
        "고스트페이스": ["ghostface"],
        "고죠": ["satoru gojo"],
        "고죠사토루": ["satoru gojo"],
        "고지라": ["godzilla"],
        "곤프릭스": ["gon freecss"],
        "길몬": ["guilmon"],
        "나나미": ["nana7mi", "nanami"],
        "나나치": ["nanachi"],
        "나비아": ["navia"],
        "나이트": ["knight"],
        "나츠미": ["natsumi"],
        "나히다": ["nahida"],
        "널릿지": ["patchouli knowledge"],
        "네모": ["nemo"],
        "네온": ["neon"],
        "노간주": ["alder"],
        "노바": ["nova"],
        "녹스": ["nox"],
        "농담곰": ["joke bear"],
        "누카": ["nuka"],
        "뉴로사마": ["neuro-sama"],
        "니들": ["needle"],
        "니모": ["nemo"],
        "다이아몬드": ["diamond"],
        "다이애나": ["diana"],
        "다크니스": ["darkness"],
        "더스트": ["dust"],
        "데니아": ["denia"],
        "데몬": ["demon"],
        "데이브": ["dave"],
        "도나텔로": ["donatello"],
        "도라에몽": ["doraemon"],
        "도베르만": ["doberman"],
        "도비": ["dobby"],
        "도트": ["dot"],
        "동키": ["donkey"],
        "동키콩": ["donkey kong"],
        "두부": ["tofu"],
        "듀크몬": ["gallantmon"],
        "드래곤": ["spyro"],
        "디노": ["dino"],
        "뚱이": ["patrick star"],
        "라이스": ["rice shower"],
        "라이스샤워": ["rice shower"],
        "란슬롯": ["lancelot"],
        "랄로": ["lalo salamanca"],
        "랄로살라망카": ["lalo salamanca"],
        "래빗": ["rabbit"],
        "레드": ["red"],
        "레몬": ["lemon"],
        "레미엘": ["remielle dan"],
        "레미엘댄": ["remielle dan"],
        "레오": ["leo"],
        "레오나르도": ["leonardo"],
        "레이": ["rei ayanami"],
        "레이센": ["ridge"],
        "레제": ["reze"],
        "렉스": ["rex"],
        "렝가": ["rengar"],
        "로런스": ["laurie"],
        "로리": ["laurie"],
        "로리로런스": ["laurie"],
        "로미오": ["romeo"],
        "로보캅": ["robocop"],
        "로빈": ["robin"],
        "로즈": ["rose"],
        "로켓": ["rocket"],
        "로키": ["rocky"],
        "록시": ["roxy migurdia"],
        "록시미굴디아": ["roxy migurdia"],
        "롤로노아": ["roronoa zoro"],
        "롤로노아조로": ["roronoa zoro"],
        "루나": ["luna"],
        "루미": ["lumi"],
        "루비": ["ruby"],
        "루시드": ["lucid"],
        "루이": ["louie"],
        "루카": ["luka"],
        "룰루": ["lulu"],
        "리쿠": ["riku"],
        "리화": ["lihua"],
        "릭산체스": ["rick sanchez"],
        "린네아": ["linnea"],
        "링크": ["link"],
        "마도카": ["madoka kaname"],
        "마리": ["marie"],
        "마린": ["marin"],
        "마오": ["mallow"],
        "마오마오": ["maomao"],
        "마우스": ["jerry"],
        "마키마": ["makima"],
        "마티": ["marty"],
        "머머": ["murmur"],
        "모르가나": ["morgana"],
        "모모": ["momo"],
        "모몬가": ["momonga"],
        "모스": ["moss"],
        "몽셰르": ["luna"],
        "미굴디아": ["roxy migurdia"],
        "미스트": ["mist"],
        "미코": ["yae miko"],
        "미쿠": ["hatsune miku"],
        "바이올렛": ["viola"],
        "바이퍼": ["viper"],
        "반디": ["firefly"],
        "백로": ["bailu"],
        "밴디쿳": ["crash bandicoot"],
        "밴시": ["vivian banshee"],
        "버블": ["bubbles"],
        "버즈": ["buzz"],
        "범블비": ["bumblebee"],
        "베가": ["vega"],
        "베르무트": ["vermouth"],
        "베아트리스": ["beatrice"],
        "베아트리체": ["beatrice"],
        "베이비": ["baby"],
        "볼트": ["bolt"],
        "부리부리자에몽": ["buriburizaemon"],
        "브로냐": ["bronya"],
        "브로리": ["broly"],
        "브루노": ["bruno"],
        "블랙": ["black cat"],
        "블랙캣": ["black cat"],
        "블레이드": ["blade"],
        "비모": ["bmo"],
        "비비안": ["vivian banshee"],
        "비비안밴시": ["vivian banshee"],
        "비에고": ["viego"],
        "뽀빠이": ["popeye"],
        "사라": ["sara"],
        "사만다": ["samantha"],
        "사보": ["sabo"],
        "사스케": ["sasuke uchiha"],
        "사유": ["sayu"],
        "사이": ["sai"],
        "사이버": ["cyber"],
        "사이타마": ["saitama"],
        "사쿠라": ["futaba sakura"],
        "사쿠라후타바": ["futaba sakura"],
        "사토루": ["satoru gojo"],
        "산체스": ["rick sanchez"],
        "살라망카": ["hector salamanca", "lalo salamanca"],
        "샤워": ["rice shower"],
        "세나": ["senna"],
        "세이나": ["noya"],
        "세이운": ["seiun sky"],
        "세이운스카이": ["seiun sky"],
        "세이지": ["sage"],
        "세피로스": ["sephiroth"],
        "셀레네": ["selene"],
        "셸리": ["shelly"],
        "소라": ["sora"],
        "손오공": ["goku"],
        "손오반": ["gohan"],
        "솔라눔": ["solanum"],
        "솔저": ["soldier"],
        "솔트": ["salt"],
        "쉐프": ["chef"],
        "쉬라몬": ["gomamon"],
        "스레너디": ["threnody"],
        "스즈미야": ["haruhi suzumiya"],
        "스즈미야하루히": ["haruhi suzumiya"],
        "스카이": ["seiun sky", "sky"],
        "스커크": ["skirk"],
        "스케어크로": ["scarecrow"],
        "스쿠터": ["scooter"],
        "스타더스트": ["stardust"],
        "스텔라": ["stella"],
        "스티브": ["steve"],
        "스파이로": ["spyro"],
        "스파이로더드래곤": ["spyro"],
        "스파이크": ["spike"],
        "스폰": ["spawn"],
        "시노부": ["shinobu"],
        "시드": ["seed"],
        "시류": ["shiryu"],
        "시시아": ["cissia"],
        "시저": ["caesar"],
        "시카다": ["cicada"],
        "시키": ["shiki"],
        "시틀라리": ["citlali"],
        "실버": ["silver"],
        "실크": ["silk"],
        "실피에트": ["sylphiette"],
        "심바": ["simba"],
        "아구몬": ["agumon"],
        "아논": ["anon chihaya"],
        "아누비스": ["anubis"],
        "아르토리아": ["saber"],
        "아르토리아펜드래건": ["saber"],
        "아마기": ["amagi"],
        "아메리카": ["captain america"],
        "아미야": ["amiya"],
        "아서": ["arthur"],
        "아스트라": ["astra", "astra yao"],
        "아스트라야오": ["astra yao"],
        "아야나미": ["rei ayanami"],
        "아야나미레이": ["rei ayanami"],
        "아야메": ["iris"],
        "아우라": ["aura"],
        "아우렐리온": ["aurelion sol"],
        "아우렐리온솔": ["aurelion sol"],
        "아우로라": ["aurora"],
        "아이": ["ai haibara", "ai hoshino"],
        "아이리스": ["iris"],
        "아이스": ["ice"],
        "아쿠아": ["aqua"],
        "아톰": ["atom"],
        "안나": ["anna"],
        "알렉스": ["alex"],
        "알베도": ["albedo"],
        "애머시스트": ["amethyst"],
        "애플잭": ["applejack"],
        "야란": ["yelan"],
        "야무치": ["yamcha"],
        "야스오": ["yasuo"],
        "야에": ["yae miko"],
        "야에미코": ["yae miko"],
        "야오": ["astra yao"],
        "엉클": ["uncle sam"],
        "엉클샘": ["uncle sam"],
        "에드워드": ["edward elric"],
        "에드워드엘릭": ["edward elric"],
        "에렌": ["eren", "eren yeager"],
        "에렌예거": ["eren yeager"],
        "에리스": ["eris"],
        "에마": ["emma"],
        "에밀리아": ["emilia"],
        "에바네시아": ["evanescia"],
        "에버나이트": ["evernight"],
        "에스테르": ["esther"],
        "에이메스": ["aemeath"],
        "에이미": ["amy"],
        "에코": ["echo"],
        "엑토르": ["hector salamanca"],
        "엑토르살라망카": ["hector salamanca"],
        "엔비": ["envy"],
        "엘릭": ["edward elric"],
        "엠버": ["amber"],
        "역무원": ["porter"],
        "예거": ["eren yeager"],
        "예수": ["jesus"],
        "오공": ["wukong"],
        "오로라": ["aurora"],
        "오르페우스": ["orpheus"],
        "오리가미": ["origami tobiichi"],
        "오브": ["orb"],
        "옵시디언": ["obsidian"],
        "옵티머스": ["optimus prime"],
        "옵티머스프라임": ["optimus prime"],
        "요이미야": ["yoimiya"],
        "우치하": ["sasuke uchiha"],
        "우치하사스케": ["sasuke uchiha"],
        "울트라": ["ultraman"],
        "울트라맨": ["ultraman"],
        "위저드": ["wizard"],
        "위즈": ["wiz"],
        "윈스턴": ["winston"],
        "유에": ["yue"],
        "유이": ["yui"],
        "유지": ["yuji itadori"],
        "의현": ["yixuan"],
        "이나리": ["inari"],
        "이누야샤": ["inuyasha"],
        "이로하": ["iroha"],
        "이소요": ["li xiaoyao"],
        "이슬": ["misty"],
        "이타도리": ["yuji itadori"],
        "이타도리유지": ["yuji itadori"],
        "일레븐": ["eleven"],
        "잉크": ["ink"],
        "전율의": ["tatsumaki"],
        "전율의타츠마키": ["tatsumaki"],
        "제니": ["jenny"],
        "제드": ["zed"],
        "제로": ["zero"],
        "제로투": ["zero two"],
        "제리": ["jerry"],
        "제리마우스": ["jerry"],
        "제시": ["jesse pinkman"],
        "제시핑크먼": ["jesse pinkman"],
        "제이드": ["jade"],
        "제이슨": ["jason"],
        "제이슨크로스": ["jason"],
        "젠제": ["sense"],
        "젠틀": ["gentle"],
        "조너선": ["jonathan"],
        "조로": ["roronoa zoro"],
        "조이": ["zoe"],
        "조이드버그": ["zoidberg"],
        "조지아": ["georgia"],
        "지우의": ["pikachu"],
        "지우의피카츄": ["pikachu"],
        "징크스": ["jinx"],
        "체리": ["cherry"],
        "최이슬": ["misty"],
        "치토세": ["chitose"],
        "치하야": ["anon chihaya"],
        "치하야아논": ["anon chihaya"],
        "카나메": ["madoka kaname"],
        "카나메마도카": ["madoka kaname"],
        "카디널": ["cardinal"],
        "카스토리스": ["castorice"],
        "카이": ["kai"],
        "캐런": ["karen"],
        "캐럿": ["carrot"],
        "캐시": ["cathy"],
        "캐피": ["cappy"],
        "캡틴": ["captain america"],
        "캡틴아메리카": ["captain america"],
        "커비": ["kirby"],
        "케빈": ["kevin"],
        "코멧": ["comet"],
        "코세어": ["corsair"],
        "코코": ["coco", "koko"],
        "코코로": ["kokoro"],
        "코튼": ["cotton"],
        "코하쿠": ["amber"],
        "쿠라마": ["kurama"],
        "쿠로": ["kuro"],
        "쿠로미": ["kuromi"],
        "쿠마": ["kuma"],
        "크라피카": ["kurapika"],
        "크래쉬": ["crash bandicoot"],
        "크래쉬밴디쿳": ["crash bandicoot"],
        "크로": ["kuro"],
        "크로스": ["jason"],
        "크리스털": ["crystal"],
        "클라우드": ["cloud"],
        "클레": ["klee"],
        "클레르": ["claire"],
        "클로드": ["claude"],
        "클로린드": ["clorinde"],
        "키니치": ["kinich"],
        "키사라": ["kisara"],
        "키위": ["kiwi"],
        "키키": ["kiki"],
        "타디스": ["tardis"],
        "타마": ["tama"],
        "타츠마키": ["tatsumaki"],
        "테나": ["tenna"],
        "텐타몬": ["tentomon"],
        "토마스": ["thomas"],
        "토머스": ["thomas"],
        "토비이치": ["origami tobiichi"],
        "토비이치오리가미": ["origami tobiichi"],
        "토토로": ["totoro"],
        "트리비": ["tribbie"],
        "파닥몬": ["patamon"],
        "파수인": ["shorekeeper"],
        "파알": ["pearl"],
        "파이로": ["pyro"],
        "파이어플라이": ["firefly"],
        "파츄리": ["patchouli knowledge"],
        "파츄리널릿지": ["patchouli knowledge"],
        "파피몬": ["gabumon"],
        "판다": ["panda"],
        "팔몬": ["palmon"],
        "패트리어트": ["patriot"],
        "팬텀": ["phantom"],
        "퍼시": ["percy"],
        "페른": ["fern"],
        "페비": ["phoebe"],
        "페이몬": ["paimon"],
        "펜드래건": ["saber"],
        "펠트": ["felt"],
        "폼폼푸린": ["pompompurin"],
        "푸리나": ["furina"],
        "프라이데이": ["friday"],
        "프라임": ["optimus prime"],
        "프리렌": ["frieren"],
        "프리즘": ["prism"],
        "프릭스": ["gon freecss"],
        "플로로": ["phrolova"],
        "플린트": ["flint"],
        "피너츠": ["snoopy"],
        "피카츄": ["pikachu"],
        "픽시": ["pixie"],
        "핑크먼": ["jesse pinkman"],
        "하루히": ["haruhi suzumiya"],
        "하이머딩거": ["heimerdinger"],
        "하이바라": ["ai haibara"],
        "하이바라아이": ["ai haibara"],
        "하이바오": ["haibao"],
        "하츠네": ["hatsune miku"],
        "하츠네미쿠": ["hatsune miku"],
        "한선우": ["jett"],
        "해피": ["happy"],
        "허수아비": ["scarecrow"],
        "헤르메스": ["hermes"],
        "헥토르": ["hector"],
        "호두": ["hu tao"],
        "호시노": ["ai hoshino"],
        "호시노아이": ["ai hoshino"],
        "호타루": ["marie"],
        "후타바": ["futaba sakura"],
        "휘틀리": ["wheatley"],
        "히메": ["pearl"],
        "히카리": ["hikari"],
    ]
}
