/// 한글 이름 → 영어·로마자 검색어. 소리로는 닿지 않는 이름(영어 이름, 한국에서 따로 부르는 이름)과 흔한 동물·사물.
/// 값은 Petdex 펫의 slug나 이름에 들어 있는 낱말이다 (소문자). 한 이름을 여러 표기로 적어 둔다.
/// Wikidata에서 만든 `generated`(scripts/update-aliases.py)에 손으로 고른 `table`을 더한다.
enum KoreanAliases {
    static let terms: [String: [String]] = {
        var map = generated
        for (names, values) in table {
            for name in names.split(separator: "/") { map[String(name), default: []] += values }
        }
        return map
    }()

    /// "한글1/한글2" → 영어 낱말들.
    private static let table: [(String, [String])] = [
        // 애니메이션·게임 캐릭터
        ("짱구/신짱/신짱구/크레용신짱/짱구는못말려", ["shin", "crayon", "shinchan", "shin-chan"]),
        ("도라에몽", ["doraemon"]),
        ("피카츄/피카추", ["pikachu"]),
        ("포켓몬/포켓몬스터", ["pokemon", "pikachu", "eevee", "gengar", "snorlax", "charmander", "bulbasaur", "squirtle"]),
        ("이브이", ["eevee"]),
        ("꼬부기", ["squirtle"]),
        ("파이리", ["charmander"]),
        ("이상해씨", ["bulbasaur"]),
        ("팬텀", ["gengar"]),
        ("잠만보", ["snorlax"]),
        ("푸린", ["jigglypuff", "purin"]),
        ("뮤", ["mew"]),
        ("고라파덕", ["psyduck"]),
        ("스누피", ["snoopy"]),
        ("스티치", ["stitch"]),
        ("미키/미키마우스", ["mickey"]),
        ("미니언/미니언즈", ["minion"]),
        ("스폰지밥/스펀지밥", ["spongebob"]),
        ("뚱이/패트릭", ["patrick"]),
        ("헬로키티/키티", ["kitty"]),
        ("마이멜로디/멜로디", ["melody"]),
        ("시나모롤", ["cinnamoroll"]),
        ("폼폼푸린", ["pompompurin", "purin"]),
        ("포차코/포챠코", ["pochacco"]),
        ("쿠로미", ["kuromi"]),
        ("커비", ["kirby"]),
        ("마리오", ["mario"]),
        ("루이지", ["luigi"]),
        ("요시", ["yoshi"]),
        ("피치/피치공주", ["peach"]),
        ("소닉", ["sonic"]),
        ("젤다", ["zelda"]),
        ("링크", ["link"]),
        ("토토로", ["totoro"]),
        ("가오나시", ["no face", "noface", "kaonashi"]),
        ("루피", ["luffy"]),
        ("쵸파/초파", ["chopper"]),
        ("조로", ["zoro"]),
        ("손오공/오공", ["goku"]),
        ("베지터", ["vegeta"]),
        ("나루토", ["naruto"]),
        ("사스케", ["sasuke"]),
        ("탄지로", ["tanjiro"]),
        ("네즈코", ["nezuko"]),
        ("고죠/고죠사토루", ["gojo"]),
        ("프리렌", ["frieren"]),
        ("아냐", ["anya"]),
        ("치이카와/먼작귀", ["chiikawa"]),
        ("하치와레", ["hachiware"]),
        ("우사기", ["usagi"]),
        ("리락쿠마", ["rilakkuma"]),
        ("가필드", ["garfield"]),
        ("톰과제리/톰", ["tom"]),
        ("제리", ["jerry"]),
        ("벅스바니", ["bugs"]),
        ("핑구", ["pingu"]),
        ("라부부", ["labubu"]),
        ("브라운", ["brown"]),
        ("스티브/마인크래프트", ["steve", "minecraft"]),
        ("클로드", ["claude"]),
        ("코덱스", ["codex"]),
        // 동물
        ("고양이/냥이/냥", ["cat", "kitty", "neko"]),
        ("강아지/개/멍멍이", ["dog", "puppy", "shiba", "corgi"]),
        ("시바/시바견", ["shiba"]),
        ("코기/웰시코기", ["corgi"]),
        ("토끼", ["rabbit", "bunny", "usagi"]),
        ("펭귄", ["penguin"]),
        ("개구리", ["frog"]),
        ("오리", ["duck"]),
        ("곰/곰돌이", ["bear"]),
        ("여우", ["fox"]),
        ("용/드래곤", ["dragon"]),
        ("로봇", ["robot"]),
        ("유령/귀신", ["ghost"]),
        ("슬라임", ["slime"]),
        ("햄스터", ["hamster"]),
        ("판다", ["panda"]),
        ("호랑이", ["tiger"]),
        ("사자", ["lion"]),
        ("부엉이/올빼미", ["owl"]),
        ("고래", ["whale"]),
        ("상어", ["shark"]),
        ("공룡", ["dino", "dinosaur"]),
        ("쥐/생쥐", ["mouse"]),
        ("고슴도치", ["hedgehog"]),
        ("수달", ["otter"]),
        ("우파루파", ["axolotl"]),
        ("병아리", ["chick"]),
        ("닭", ["chicken"]),
        ("돼지", ["pig"]),
        ("소/젖소", ["cow"]),
        ("양", ["sheep"]),
        ("원숭이", ["monkey"]),
        ("거북이/거북", ["turtle"]),
        ("문어", ["octopus"]),
        ("다람쥐", ["squirrel"]),
        ("사슴", ["deer"]),
        ("코알라", ["koala"]),
        ("물개/바다표범", ["seal"]),
        ("카피바라", ["capybara"]),
        ("너구리", ["raccoon", "tanuki"]),
        ("유니콘", ["unicorn"]),
        // 색과 꾸밈말 (고양이 검은 → cat black)
        ("검은/검정/까만/블랙", ["black"]),
        ("흰/하얀/흰색/화이트", ["white"]),
        ("빨간/빨강/레드", ["red"]),
        ("파란/파랑/블루", ["blue"]),
        ("노란/노랑/옐로", ["yellow"]),
        ("초록/녹색/그린", ["green"]),
        ("분홍/핑크", ["pink"]),
        ("보라/퍼플", ["purple"]),
        ("주황/오렌지", ["orange"]),
        ("금색/황금/골드", ["gold", "golden"]),
        ("아기/베이비", ["baby"]),
        ("미니/꼬마", ["mini", "chibi"]),
        ("귀여운", ["cute"]),
        // 그 밖
        ("쿠키", ["cookie"]),
    ]
}
